index=* sourcetype=access_combined status=404
| bin _time span=1m
| stats count as http_404_count dc(uri_path) as unique_missing_files values(uri_path) as sample_404_paths by clientip, _time
| where http_404_count > 15 AND unique_missing_files > 10
| table _time clientip http_404_count unique_missing_files sample_404_paths